CREATE TABLE PLAYER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(100) NOT NULL UNIQUE,
    profile_image VARCHAR(100),
    creation_date TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE STAT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    player_id INT NOT NULL,
    score DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (player_id) REFERENCES PLAYER(id)
);
